name: Export SLS OBP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Export SLS OBP
        shell: bash
        run: |
          pip install -r requirements.txt
          python release.py

      - name: Find all zip files
        id: files
        run: |
          files=($(ls ${{ github.workspace }}/release/*.zip))
          echo "files=${files[@]}" >> $GITHUB_OUTPUT

      - name: Upload each zip as separate artifact
        shell: bash
        run: |
          for file in ${{ github.workspace }}/release/*.zip; do
            [ -f "$file" ] || continue
            name=$(basename "$file" .zip)
            echo "Uploading $file as artifact: $name"
            gh actions upload-artifact "$file" --name "$name"
          done
