name: Export SLS OBP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      zip-files: ${{ steps.collect.outputs.zip-files }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Export SLS OBP
        run: |
          pip install -r requirements.txt
          python release.py

      # 收集所有 zip 名稱
      - name: Collect zip files
        id: collect
        run: |
          files=()
          for f in ${{ github.workspace }}/release/*.zip; do
            [ -f "$f" ] || continue
            files+=("$(basename "$f")")
          done
          echo "zip-files=${files[*]}" >> $GITHUB_OUTPUT

  upload:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        zip-file: ${{ fromJSON('["' + needs.build.outputs.zip-files.replace(' ', '","') + '"]') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload ${{ matrix.zip-file }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.zip-file }}
          path: ${{ github.workspace }}/release/${{ matrix.zip-file }}
