name: Export SLS OBP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Export SLS OBP
        shell: bash
        run: |
          pip install -r requirements.txt
          python release.py

      - name: Upload each zip separately
        id: upload-zips
        run: |
          mkdir -p temp-artifacts
          for zipfile in ${{ github.workspace }}/release/*.zip; do
            [ -f "$zipfile" ] || continue
            artifact_name=$(basename "$zipfile" .zip)
            mkdir -p "temp-artifacts/$artifact_name"
            cp "$zipfile" "temp-artifacts/$artifact_name/"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: temp-artifacts/*
