name: Export SLS OBP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Export SLS OBP
        shell: bash
        run: |
          pip install -r requirements.txt
          python release.py

      - name: Find all zip files
        id: find_zips
        run: |
          echo "files="
          for f in ${{ github.workspace }}/release/*.zip; do
            if [ -f "$f" ]; then
              echo "files<<EOF" >> $GITHUB_OUTPUT
              echo "$f" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
            fi
          done

      - name: Upload artifacts
        shell: bash
        run: |
          for zipfile in ${{ github.workspace }}/release/*.zip; do
            [ -f "$zipfile" ] || continue
            artifact_name=$(basename "$zipfile" .zip)
            echo "Uploading $zipfile as artifact: $artifact_name"
            gh workflow run upload-artifact \
              --name "$artifact_name" \
              --path "$zipfile"
          done
